<?php 
/**
 *******************************************************************************
 * File:   capswitch.php
 * Author: Shawn Haigh
 *  
 * Decsription:  Implements a simple currencly converter - PHP 5.4.36
 *******************************************************************************
 */


/**
* Main currecny conversion class, outputs the converted currency, 
* santizes input, and handles errors.
*
* Basic usage:
* require 'path/<thisFile>';'
* $cs = new capswtich;
* $cs->convert( str $sourceCurrency, str $targetCurrency, int amountToConvert);
*
* Parameters
* 
* sourceCurrency: String, 3 character ISO 4217 currency code
* targetCurrency: String, 3 character ISO 4217 currency code
* amountToConvert: Float, An amount to convert.
*
*/
class capswitch
{

  // Curency rates relative to the EUR
  private $_exchrate = array(
    'EUR' => 1,           //base rate
    'USD' => 1.5897,
    'CHF' => 1.6135,
    'GBP' => 0.8031,
    'JPY' => 164.549847,  // USD * JPY = JPY rate relative to EUR 
    'CAD' => 1.61800557   // GBP * CAD = CAD rate relative to EUR
    );
  public $errors = array();

  /*
    Function to convert one currency to another.
    Accepts three arguments:
    from: (string) an ISO 4217 currency code
    to: (string) an ISO 4217 currency code
    amount: (int) amount to convert
    returns a string
  */
  public function convert($from, $to, $amount) 
  {
    
    // are there errors?
    if ( count($this->errors) ) {
      return 0;
    }
    
    /** Checks passed, on to main conversion
     ***************************************************************************
     */
      
      if ($to == "EUR") {
        
        // converting to EUR, find inverse of currency
        $value = $amount * ( 1 / $this->_exchrate[$from]) / $this->_exchrate[$to];
        
        } else {
          
          // normal conversion calaulation
          $value= $amount * $this->_exchrate[$to] / $this->_exchrate[$from];
        
        }

      // round up to 2 significant digits
      $value = round($value, 2); 
      
      // english number format, truncate to two decimal places
      $value = number_format($value, 2, ".", ",");
      
      // Append target Currentcy code
      $value = $value . ' ' . $to; 

      return $value;

  }

  /*
    Get a list of currency codes
    Returns an array
  */
  public function getCurrencies()
  {
    return array_keys($this->_exchrate);
  }

  /*
    Validates ISO currecny code and verifies if the ISO code exists in _exchrate
    Returns a string
  */
  public function validateCode($iso, $orig) 
  {
    // Verify if the exchange rate is valid and exists.
    if (!preg_match('/[A-Z][A-Z][A-Z]/', $iso) || !array_key_exists($iso, $this->_exchrate)) 
    {
      $this->errors[] = "Invalid, exchange rate ISO code in <b>$orig</b>";
      return "";
    }

    return $iso;
    
  }

  /*
    Validates wheater input is a number

    Returns a number
  */
  public function validateNum($num)
  {
    
    if (!is_numeric($num))
    {
      $this->errors[] = "Invalid, <b>amount</b> must be an integer";
      return 0;
    }
    
    return $num;

  }

  /*
    Outputs any errors generated by the validation methods

    returns a string
  */
  public function getErrors()
  {
    if ( count($this->errors) ) 
    {
      foreach ($this->errors as $mesage) {
        echo $mesage . "<br/>";
      }
    }
  }

}